version: '3'

services:
  promotv_rc:
    image: registry-gitlab.profintel.ru/profintel/promotv:latest
    ports:
      - '8030:3000'
    container_name: promotv_rc
    restart: always
    logging:
      driver: syslog
      options:
        syslog-facility: 'local0'
        tag: 'promotv_rc'
  promotv_prod:
    image: registry-gitlab.profintel.ru/profintel/promotv:latest
    ports:
      - '8031:3000'
    container_name: promotv_prod
    restart: always
    logging:
      driver: syslog
      options:
        syslog-facility: 'local0'
        tag: 'promotv_prod'
